/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessRouteImport } from './routes/assess'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ActionPlanIdRouteImport } from './routes/action-plan.$id'
import { Route as AssessmentIdRouteImport } from './routes/assessment.$id'
import { Route as EmergencyIndexRouteImport } from './routes/emergency.index'
import { Route as EmergencyActiveRouteImport } from './routes/emergency.active'
import { Route as ReportIdRouteImport } from './routes/report.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessRoute = AssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionPlanIdRoute = ActionPlanIdRouteImport.update({
  id: '/action-plan/$id',
  path: '/action-plan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdRoute = AssessmentIdRouteImport.update({
  id: '/assessment/$id',
  path: '/assessment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyIndexRoute = EmergencyIndexRouteImport.update({
  id: '/emergency/',
  path: '/emergency/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyActiveRoute = EmergencyActiveRouteImport.update({
  id: '/emergency/active',
  path: '/emergency/active',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/assistant': typeof AssistantRoute
  '/checkin': typeof CheckinRoute
  '/contacts': typeof ContactsRoute
  '/history': typeof HistoryRoute
  '/journey': typeof JourneyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/action-plan/$id': typeof ActionPlanIdRoute
  '/assessment/$id': typeof AssessmentIdRoute
  '/emergency/active': typeof EmergencyActiveRoute
  '/report/$id': typeof ReportIdRoute
  '/emergency/': typeof EmergencyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/assistant': typeof AssistantRoute
  '/checkin': typeof CheckinRoute
  '/contacts': typeof ContactsRoute
  '/history': typeof HistoryRoute
  '/journey': typeof JourneyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/action-plan/$id': typeof ActionPlanIdRoute
  '/assessment/$id': typeof AssessmentIdRoute
  '/emergency/active': typeof EmergencyActiveRoute
  '/report/$id': typeof ReportIdRoute
  '/emergency': typeof EmergencyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/assistant': typeof AssistantRoute
  '/checkin': typeof CheckinRoute
  '/contacts': typeof ContactsRoute
  '/history': typeof HistoryRoute
  '/journey': typeof JourneyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/action-plan/$id': typeof ActionPlanIdRoute
  '/assessment/$id': typeof AssessmentIdRoute
  '/emergency/active': typeof EmergencyActiveRoute
  '/report/$id': typeof ReportIdRoute
  '/emergency/': typeof EmergencyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assess'
    | '/assistant'
    | '/checkin'
    | '/contacts'
    | '/history'
    | '/journey'
    | '/resources'
    | '/services'
    | '/settings'
    | '/action-plan/$id'
    | '/assessment/$id'
    | '/emergency/active'
    | '/report/$id'
    | '/emergency/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assess'
    | '/assistant'
    | '/checkin'
    | '/contacts'
    | '/history'
    | '/journey'
    | '/resources'
    | '/services'
    | '/settings'
    | '/action-plan/$id'
    | '/assessment/$id'
    | '/emergency/active'
    | '/report/$id'
    | '/emergency'
  id:
    | '__root__'
    | '/'
    | '/assess'
    | '/assistant'
    | '/checkin'
    | '/contacts'
    | '/history'
    | '/journey'
    | '/resources'
    | '/services'
    | '/settings'
    | '/action-plan/$id'
    | '/assessment/$id'
    | '/emergency/active'
    | '/report/$id'
    | '/emergency/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessRoute: typeof AssessRoute
  AssistantRoute: typeof AssistantRoute
  CheckinRoute: typeof CheckinRoute
  ContactsRoute: typeof ContactsRoute
  HistoryRoute: typeof HistoryRoute
  JourneyRoute: typeof JourneyRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  ActionPlanIdRoute: typeof ActionPlanIdRoute
  AssessmentIdRoute: typeof AssessmentIdRoute
  EmergencyActiveRoute: typeof EmergencyActiveRoute
  ReportIdRoute: typeof ReportIdRoute
  EmergencyIndexRoute: typeof EmergencyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess': {
      id: '/assess'
      path: '/assess'
      fullPath: '/assess'
      preLoaderRoute: typeof AssessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-plan/$id': {
      id: '/action-plan/$id'
      path: '/action-plan/$id'
      fullPath: '/action-plan/$id'
      preLoaderRoute: typeof ActionPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id': {
      id: '/assessment/$id'
      path: '/assessment/$id'
      fullPath: '/assessment/$id'
      preLoaderRoute: typeof AssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/': {
      id: '/emergency/'
      path: '/emergency'
      fullPath: '/emergency/'
      preLoaderRoute: typeof EmergencyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/active': {
      id: '/emergency/active'
      path: '/emergency/active'
      fullPath: '/emergency/active'
      preLoaderRoute: typeof EmergencyActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessRoute: AssessRoute,
  AssistantRoute: AssistantRoute,
  CheckinRoute: CheckinRoute,
  ContactsRoute: ContactsRoute,
  HistoryRoute: HistoryRoute,
  JourneyRoute: JourneyRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  ActionPlanIdRoute: ActionPlanIdRoute,
  AssessmentIdRoute: AssessmentIdRoute,
  EmergencyActiveRoute: EmergencyActiveRoute,
  ReportIdRoute: ReportIdRoute,
  EmergencyIndexRoute: EmergencyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
