import { createFileRoute, Link } from "@tanstack/react-router";
import { Download, Save, Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useStore } from "@/lib/store";
import { RiskBadge } from "@/components/safety/RiskScore";
import { RiskBreakdown } from "@/components/safety/RiskBreakdown";
import { EmergencyButton } from "@/components/safety/EmergencyButton";
import { EmptyState } from "@/routes/index";
import { toast } from "sonner";

export const Route = createFileRoute("/report/$id")({
  head: () => ({
    meta: [
      { title: "Incident Report — SuRaksha AI" },
      {
        name: "description",
        content:
          "A structured, AI-generated incident report with detected indicators, evidence, recommended actions and escalation guidance.",
      },
      { property: "og:title", content: "Incident Report — SuRaksha AI" },
      { property: "og:description", content: "Documented, shareable safety incident record." },
    ],
  }),
  component: ReportPage,
});

function ReportPage() {
  const { id } = Route.useParams();
  const { incidents, updateIncident } = useStore();
  const incident = incidents.find((i) => i.id === id);

  if (!incident)
    return <EmptyState title="Report not found" body="This incident is no longer available." />;

  const download = () => {
    const lines = [
      "SuRaksha AI — Incident Report (Prototype)",
      "=========================================",
      `Incident ID: ${incident.id}`,
      `Date & Time: ${new Date(incident.createdAt).toLocaleString("en-IN")}`,
      `Incident Type: ${incident.type}`,
      `Risk Score: ${incident.riskScore}/100`,
      `Risk Level: ${incident.riskLevel}`,
      "",
      "Incident Summary",
      incident.assessment.summary,
      "",
      "Description",
      incident.description || "(not provided)",
      "",
      "Detected Indicators",
      ...incident.assessment.indicators.map((i) => `- ${i.label} (${i.severity})`),
      "",
      "Risk Breakdown",
      ...incident.assessment.factors.map((f) => `- ${f.label}: ${f.score}/${f.max}`),
      "",
      "Evidence",
      ...(incident.evidence.length
        ? incident.evidence.map((e) => `- ${e.fileName}`)
        : ["- none attached"]),
      "",
      "Recommended Actions",
      ...incident.assessment.actions.map((a) => `${a.priority}. ${a.title} — ${a.description}`),
      "",
      "Escalation Recommendation",
      incident.assessment.escalation,
      "",
      "This document is generated by a prototype for demonstration purposes.",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${incident.id}-suraksha-report.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report downloaded");
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">
            AI-Generated Incident Report
          </p>
          <h1 className="mt-1 text-2xl font-bold tracking-tight lg:text-3xl">{incident.type}</h1>
        </div>
        <RiskBadge level={incident.riskLevel} score={incident.riskScore} />
      </div>

      <section className="panel grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-3">
        <Field label="Incident ID" value={incident.id} />
        <Field label="Date & Time" value={new Date(incident.createdAt).toLocaleString("en-IN")} />
        <Field label="Incident Type" value={incident.type} />
        <Field label="Risk Score" value={`${incident.riskScore} / 100`} />
        <Field label="Risk Level" value={incident.riskLevel} />
        <Field label="Status" value={incident.status} />
      </section>

      <section className="panel space-y-2 p-5">
        <h2 className="text-base font-semibold">Incident Summary</h2>
        <p className="text-sm text-muted-foreground">{incident.assessment.summary}</p>
        {incident.description ? (
          <p className="rounded-xl bg-secondary p-3 text-sm italic">
            &ldquo;{incident.description}&rdquo;
          </p>
        ) : null}
      </section>

      <div className="grid gap-6 lg:grid-cols-2">
        <section className="panel p-5">
          <h2 className="mb-3 text-base font-semibold">Detected Indicators</h2>
          <ul className="space-y-2 text-sm">
            {incident.assessment.indicators.map((i) => (
              <li
                key={i.label}
                className="flex items-center justify-between rounded-lg bg-secondary px-3 py-2"
              >
                <span>{i.label}</span>
                <span className="text-xs font-semibold text-muted-foreground">{i.severity}</span>
              </li>
            ))}
          </ul>
        </section>
        <section className="panel p-5">
          <h2 className="mb-3 text-base font-semibold">Evidence</h2>
          {incident.evidence.length ? (
            <ul className="grid gap-2">
              {incident.evidence.map((e) => (
                <li key={e.id} className="rounded-xl border border-border p-3 text-sm">
                  <p className="font-medium">{e.fileName}</p>
                  <p className="text-xs text-muted-foreground">
                    {e.fileType} · {new Date(e.uploadedAt).toLocaleString("en-IN")}
                  </p>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-muted-foreground">No evidence attached to this incident.</p>
          )}
        </section>
      </div>

      <section className="panel p-5">
        <h2 className="mb-4 text-base font-semibold">Risk Breakdown</h2>
        <RiskBreakdown factors={incident.assessment.factors} total={incident.riskScore} />
      </section>

      <section className="panel p-5">
        <h2 className="mb-3 text-base font-semibold">Recommended Actions</h2>
        <ol className="space-y-2 text-sm">
          {incident.assessment.actions.map((a) => (
            <li key={a.id}>
              <span className="font-medium">
                {a.priority}. {a.title}
              </span>{" "}
              <span className="text-muted-foreground">— {a.description}</span>
            </li>
          ))}
        </ol>
      </section>

      <section className="panel p-5">
        <h2 className="text-base font-semibold">Escalation Recommendation</h2>
        <p className="mt-2 text-sm text-muted-foreground">{incident.assessment.escalation}</p>
      </section>

      <div className="flex flex-wrap gap-3">
        <Button
          onClick={() => {
            updateIncident(incident.id, { status: "Report Generated" });
            toast.success("Report saved to your safety history");
          }}
        >
          <Save className="mr-2 h-4 w-4" /> Save Report
        </Button>
        <Button variant="outline" onClick={download}>
          <Download className="mr-2 h-4 w-4" /> Download Report
        </Button>
        <Button
          variant="outline"
          onClick={() =>
            toast.success("Simulated: secure share link prepared for your trusted contact")
          }
        >
          <Share2 className="mr-2 h-4 w-4" /> Share Report
        </Button>
        <Button asChild variant="secondary">
          <Link to="/action-plan/$id" params={{ id: incident.id }}>
            View Action Plan
          </Link>
        </Button>
        <EmergencyButton />
      </div>
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p>
      <p className="mt-0.5 text-sm font-semibold">{value}</p>
    </div>
  );
}
